config/routes.rb
Rails.application.routes.draw do
  # Databases
  resources :crews
  resources :movies
  resources :users
  resources :purchasings
  resources :theaters

  # Get routes
  get '/theater_map/map', to: 'theater_map#map', as: 'theater_map'
  get '/show_movie/show_movie'
  get 'admin_dashboard/index', as: 'admin_dashboard'
  get 'sessions/new'
  get 'session/new'

  # Users routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Search routes
  get '/search/movie', to: 'search#movie', as: 'search_movie'
  get '/search/crew', to: 'search#crew', as: 'search_crew'
  get '/search/theater', to: 'search#theater', as: 'search_theater'
  get '/search/top_to_movies', to: 'search#top_10_movies', as: 'top_10_movies'

  # Route for movie info after thumbnail button click
  get '/show_movie/:id', to: 'show_movie#show_movie', as: 'show_movie'

  # Homepage route
  root 'moviefy#index'
end

app/models/purchasing.rb
class Purchasing < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  belongs_to :theater
  validates :name_on_card, :exp_year, :exp_month, :street, :city, :state, :num_of_tickets, :movie_id, :theater_id, :user_id, presence: true
  validates :card_num, presence: true, length: { is: 16 }
  validates :zipcode, presence: true, length: { is: 5 }
  validates :security_code, presence: true, length: { is: 3 }
end

app/controllers/purchasings_controller.rb
class PurchasingsController < ApplicationController
  before_action :set_purchasing, only: [:show, :edit, :update, :destroy]

  # GET /purchasings
  # GET /purchasings.json
  def index
    @purchasings = Purchasing.all
  end

  # GET /purchasings/1
  # GET /purchasings/1.json
  def show
  end

  # GET /purchasings/new
  def new
    @purchasing = Purchasing.new
    @theaters = Theater.all
    @movies = Movie.all
  end

  # GET /purchasings/1/edit
  def edit
    @movies = Movie.all
    @theaters = Theater.all
  end

  # POST /purchasings
  # POST /purchasings.json
  def create
    @movies = Movie.all
    @theaters = Theater.all
    @purchasing = Purchasing.new(purchasing_params)

    respond_to do |format|
      if @purchasing.save
        format.html { redirect_to @purchasing, notice: 'Purchasing was successfully created.' }
        format.json { render :show, status: :created, location: @purchasing }
      else
        format.html { render :new }
        format.json { render json: @purchasing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchasings/1
  # PATCH/PUT /purchasings/1.json
  def update
    respond_to do |format|
      if @purchasing.update(purchasing_params)
        format.html { redirect_to @purchasing, notice: 'Purchasing was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchasing }
      else
        format.html { render :edit }
        format.json { render json: @purchasing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchasings/1
  # DELETE /purchasings/1.json
  def destroy
    @purchasing.destroy
    respond_to do |format|
      format.html { redirect_to purchasings_url, notice: 'Purchasing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchasing
      @purchasing = Purchasing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchasing_params
      params.require(:purchasing).permit(:num_of_tickets, :movie_id, :theater_id, :user_id, :name_on_card, :card_num, :exp_month, :exp_year, :security_code, :street, :city, :state, :zipcode, :total)
    end
end

app/helpers/purchasings_helper.rb
module PurchasingsHelper
end

app/views/purchasings/_form.html.erb
<%= form_with(model: @purchasing, local: true) do |form| %>
  <% if @purchasing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchasing.errors.count, "error") %> prohibited this purchasing from being saved:</h2>

      <ul>
      <% purchasing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Credit Card</h3>
  <div class="field">
    <%= form.label :name_on_card %>
    <%= form.text_field :name_on_card %>
  </div>

  <div class="field">
    <%= form.label 'Card Number' %>
    <%= form.number_field :card_num %>
  </div>

  <div class="field">
    <%= form.label 'Expiration Date' %>
    <%= form.select :exp_month, 1..12, :include_blank => true %>
    <%= form.select :exp_year, Date.today.year..10.years.from_now.year, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :security_code %>
    <%= form.number_field :security_code %>
  </div>

  <hr>

  <h3>Billing Address</h3>
  <div class="field">
    <%= form.label 'Street Address' %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.number_field :zipcode %>
  </div>

  <hr>

  <h3>Ticket</h3>
  <div class="field">
    <%= form.label 'Number of Tickets' %>
    <%= form.number_field :num_of_tickets, :id => 'num_of_tickets', :onchange => 'myFunction()' %>
    <%= form.label "One ticket is $12, your Total is:" %>
    <b><%= form.label '$0' , :id => 'total'%></b>
    <%= form.hidden_field :total, :id => 'total-2' %>
  </div>

  <!-- to calculate the total number of tickets-->
  <script>
  function myFunction() {
      var x = document.getElementById('num_of_tickets').value;
      var total = x * 12;
      document.getElementById("total").innerHTML = '$' + total;
      document.getElementById("total-2").value = total;
  }
  </script>

  <div class="field">
    <%= form.label 'Movie:' %>
    <% if !params[:movie_id] %>
      <%= form.collection_select(:movie_id, @movies, :id, :movie_title, :include_blank => true) %>
    <% else %>
      <% movie = Movie.find(params[:movie_id]) %>
      <% puts 'hi'%>
      <%puts movie.movie_title%>
      <% movie_title = movie.movie_title %>
      <%= form.label movie_title %>
      <%= form.hidden_field :movie_id, :value => params[:movie_id] %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label 'Theater' %>
    <%= form.collection_select(:theater_id, Theater.all.map{|a| ["#{a.state}, #{a.city}, #{a.zipcode}, #{a.theater_name}", a.id]}, :second, :first) %>

  </div>

  <%= form.hidden_field :user_id, :value => session[:user_id] %>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/purchasings/edit.html.erb
<h1>Editing Purchasing</h1>

<%= render 'form', purchasing: @purchasing %>

<%= link_to 'Show', @purchasing %> |
<% if admin? %>
  <%= link_to 'Back', purchasings_path %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/purchasings/index.html.erb
<p id="notice"><%= notice %></p>

<% if admin? %>

  <h1>Purchasings</h1>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Number of tickets</th>
        <th>Total in $</th>
        <th>Movie</th>
        <th>Theater Name</th>
        <th>Theater Zipcode</th>
        <th>Theater City</th>
        <th>Theater State</th>
        <th>Member since</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @purchasings.each do |purchasing| %>
        <tr>
          <td><%= purchasing.user.first_name %> <%= purchasing.user.last_name %></td>
          <td><%= purchasing.num_of_tickets %></td>
          <td><%= purchasing.total %></td>
          <td><%= purchasing.movie.movie_title %></td>
          <td><%= purchasing.theater.theater_name %></td>
          <td><%= purchasing.theater.zipcode %></td>
          <td><%= purchasing.theater.city%></td>
          <td><%= purchasing.theater.state %></td>
          <td><%= purchasing.user.created_at %></td>
          <td><%= link_to 'Show', purchasing %></td>
          <td><%= link_to 'Edit', edit_purchasing_path(purchasing) %></td>
          <td><%= link_to 'Destroy', purchasing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Back', admin_dashboard_path %> |
  <%= link_to 'New Purchasing', new_purchasing_path %>

<% end %>

app/views/purchasings/new.html.erb
<h1>Purchase Movie Ticket</h1><br>

<%= render 'form', purchasing: @purchasing %>
<br>
<%= link_to 'Back', root_path %>

app/views/purchasings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User Name:</strong>
  <%= @purchasing.user.first_name %> <%= @purchasing.user.last_name %>
</p>

<p>
  <strong>Number of tickets:</strong>
  <%= @purchasing.num_of_tickets %>
</p>

<p>
  <strong><th>Total in $:</strong>
  <%= @purchasing.total %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @purchasing.movie.movie_title %>
</p>

<p>
  <strong>Theater Name:</strong>
  <%= @purchasing.theater.theater_name %>
</p>

<p>
  <strong>Theater Zipcode:</strong>
  <%= @purchasing.theater.zipcode %>
</p>

<p>
  <strong>Theater City:</strong>
  <%= @purchasing.theater.city %>
</p>

<p>
  <strong>Theater State:</strong>
  <%= @purchasing.theater.state %>
</p>

<p>
  <strong>Member Since:</strong>
  <%= @purchasing.user.created_at %>
</p>

<%= link_to 'Edit', edit_purchasing_path(@purchasing) %> |

<% if admin? %>
  <%= link_to 'Back', purchasings_path %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>