config/routes.rb
Rails.application.routes.draw do
  # Databases
  resources :crews
  resources :movies
  resources :users
  resources :purchasings
  resources :theaters

  # Get routes
  get '/theater_map/map', to: 'theater_map#map', as: 'theater_map'
  get '/show_movie/show_movie'
  get 'admin_dashboard/index', as: 'admin_dashboard'
  get 'sessions/new'
  get 'session/new'

  # Users routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Search routes
  get '/search/movie', to: 'search#movie', as: 'search_movie'
  get '/search/crew', to: 'search#crew', as: 'search_crew'
  get '/search/theater', to: 'search#theater', as: 'search_theater'
  get '/search/top_to_movies', to: 'search#top_10_movies', as: 'top_10_movies'

  # Route for movie info after thumbnail button click
  get '/show_movie/:id', to: 'show_movie#show_movie', as: 'show_movie'

  # Homepage route
  root 'moviefy#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found

  # GET /movies
  # GET /movies.json
  def index
    #@movies = Movie.all
    @movies = Movie.search(params[:filter_title], params[:filter_genre], params[:filter_key])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:movie_title, :num_critic_for_reviews, :duration, :gross, :genres, :movie_imdb_link, :num_voted_users, :facenumber_in_poster, :plot_keywords, :num_user_for_reviews, :language, :country, :content_rating, :budget, :title_year, :imdb_score, :aspect_ratio, :movie_fb_likes, :filter_title, :filter_genre, :filter_key)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :movie_title %>
    <%= form.text_field :movie_title %>
  </div>

  <div class="field">
    <%= form.label :num_critic_for_reviews %>
    <%= form.number_field :num_critic_for_reviews %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :gross %>
    <%= form.number_field :gross %>
  </div>

  <div class="field">
    <%= form.label :genres %>
    <%= form.text_field :genres %>
  </div>

  <div class="field">
    <%= form.label :movie_imdb_link %>
    <%= form.text_field :movie_imdb_link %>
  </div>

  <div class="field">
    <%= form.label :num_voted_users %>
    <%= form.number_field :num_voted_users %>
  </div>

  <div class="field">
    <%= form.label :facenumber_in_poster %>
    <%= form.number_field :facenumber_in_poster %>
  </div>

  <div class="field">
    <%= form.label :plot_keywords %>
    <%= form.text_field :plot_keywords %>
  </div>

  <div class="field">
    <%= form.label :num_user_for_reviews %>
    <%= form.number_field :num_user_for_reviews %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :content_rating %>
    <%= form.text_field :content_rating %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.number_field :budget %>
  </div>

  <div class="field">
    <%= form.label :title_year %>
    <%= form.number_field :title_year %>
  </div>

  <div class="field">
    <%= form.label :imdb_score %>
    <%= form.text_field :imdb_score %>
  </div>

  <div class="field">
    <%= form.label :aspect_ratio %>
    <%= form.text_field :aspect_ratio %>
  </div>

  <div class="field">
    <%= form.label :movie_fb_likes %>
    <%= form.number_field :movie_fb_likes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<p id="notice"><%= notice %></p>
<!-- only admin -->
<% if admin? %>
  <h1>Editing Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Show', @movie %> |
  <%= link_to 'Back', movies_path %>
<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Movie title</th>
      <th>Num critic for reviews</th>
      <th>Duration</th>
      <th>Gross</th>
      <th>Genres</th>
      <th>Movie imdb link</th>
      <th>Num voted users</th>
      <th>Facenumber in poster</th>
      <th>Plot keywords</th>
      <th>Num user for reviews</th>
      <th>Language</th>
      <th>Country</th>
      <th>Content rating</th>
      <th>Budget</th>
      <th>Title year</th>
      <th>Imdb score</th>
      <th>Aspect ratio</th>
      <th>Movie fb likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.movie_title %></td>
        <td><%= movie.num_critic_for_reviews %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.gross %></td>
        <td><%= movie.genres %></td>
        <td><%= movie.movie_imdb_link %></td>
        <td><%= movie.num_voted_users %></td>
        <td><%= movie.facenumber_in_poster %></td>
        <td><%= movie.plot_keywords %></td>
        <td><%= movie.num_user_for_reviews %></td>
        <td><%= movie.language %></td>
        <td><%= movie.country %></td>
        <td><%= movie.content_rating %></td>
        <td><%= movie.budget %></td>
        <td><%= movie.title_year %></td>
        <td><%= movie.imdb_score %></td>
        <td><%= movie.aspect_ratio %></td>
        <td><%= movie.movie_fb_likes %></td>

        <!-- link to show_movie_path -->
        <% movie_title = adjust_movie_title(movie.movie_title).titleize %>
        <td><%= link_to 'Show', show_movie_path(:id => movie_title) %></td>

        <!-- only admin -->
        <% if admin? %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- only admin -->
<% if admin? %>
  <%= link_to 'Back', admin_dashboard_path %> |
  <%= link_to 'New Movie', new_movie_path %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/movies/new.html.erb
<p id="notice"><%= notice %></p>
<!-- only admin -->
<% if admin? %>
  <h1>New Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Back', movies_path %>
<% end %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<!-- only admin -->
<% if admin? %>

  <p>
    <strong>Movie title:</strong>
    <%= @movie.movie_title %>
  </p>

  <p>
    <strong>Num critic for reviews:</strong>
    <%= @movie.num_critic_for_reviews %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= @movie.duration %>
  </p>

  <p>
    <strong>Gross:</strong>
    <%= @movie.gross %>
  </p>

  <p>
    <strong>Genres:</strong>
    <%= @movie.genres %>
  </p>

  <p>
    <strong>Movie imdb link:</strong>
    <%= @movie.movie_imdb_link %>
  </p>

  <p>
    <strong>Num voted users:</strong>
    <%= @movie.num_voted_users %>
  </p>

  <p>
    <strong>Facenumber in poster:</strong>
    <%= @movie.facenumber_in_poster %>
  </p>

  <p>
    <strong>Plot keywords:</strong>
    <%= @movie.plot_keywords %>
  </p>

  <p>
    <strong>Num user for reviews:</strong>
    <%= @movie.num_user_for_reviews %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= @movie.language %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= @movie.country %>
  </p>

  <p>
    <strong>Content rating:</strong>
    <%= @movie.content_rating %>
  </p>

  <p>
    <strong>Budget:</strong>
    <%= @movie.budget %>
  </p>

  <p>
    <strong>Title year:</strong>
    <%= @movie.title_year %>
  </p>

  <p>
    <strong>Imdb score:</strong>
    <%= @movie.imdb_score %>
  </p>

  <p>
    <strong>Aspect ratio:</strong>
    <%= @movie.aspect_ratio %>
  </p>

  <p>
    <strong>Movie fb likes:</strong>
    <%= @movie.movie_fb_likes %>
  </p>

  <%= link_to 'Edit', edit_movie_path(@movie) %> |
  <%= link_to 'Back', movies_path %>
<% end %>