config/routes.rb
Rails.application.routes.draw do
  # Databases
  resources :crews
  resources :movies
  resources :users
  resources :purchasings
  resources :theaters

  # Get routes
  get '/theater_map/map', to: 'theater_map#map', as: 'theater_map'
  get '/show_movie/show_movie'
  get 'admin_dashboard/index', as: 'admin_dashboard'
  get 'sessions/new'
  get 'session/new'

  # Users routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Search routes
  get '/search/movie', to: 'search#movie', as: 'search_movie'
  get '/search/crew', to: 'search#crew', as: 'search_crew'
  get '/search/theater', to: 'search#theater', as: 'search_theater'
  get '/search/top_to_movies', to: 'search#top_10_movies', as: 'top_10_movies'

  # Route for movie info after thumbnail button click
  get '/show_movie/:id', to: 'show_movie#show_movie', as: 'show_movie'

  # Homepage route
  root 'moviefy#index'
end

app/models/theater.rb
class Theater < ApplicationRecord

  def self.search(state=None, city=None, zipcode=None )
    if state || city|| zipcode
      where('state LIKE ? AND city LIKE ? AND zipcode LIKE ?', "%#{state}%", "%#{city}%", "%#{zipcode}%")
    else
      all
    end
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found

  # GET /theaters
  # GET /theaters.json
  def index
    #@theaters = Theater.all
    @theaters = Theater.search(params[:filter_state], params[:filter_city], params[:filter_zipcode])
  end

  # GET /theaters/1
  # GET /theaters/1.json
  def show
  end

  # GET /theaters/new
  def new
    @theater = Theater.new
  end

  # GET /theaters/1/edit
  def edit
  end

  # POST /theaters
  # POST /theaters.json
  def create
    @theater = Theater.new(theater_params)

    respond_to do |format|
      if @theater.save
        format.html { redirect_to @theater, notice: 'Theater was successfully created.' }
        format.json { render :show, status: :created, location: @theater }
      else
        format.html { render :new }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theaters/1
  # PATCH/PUT /theaters/1.json
  def update
    respond_to do |format|
      if @theater.update(theater_params)
        format.html { redirect_to @theater, notice: 'Theater was successfully updated.' }
        format.json { render :show, status: :ok, location: @theater }
      else
        format.html { render :edit }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1
  # DELETE /theaters/1.json
  def destroy
    @theater.destroy
    respond_to do |format|
      format.html { redirect_to theaters_url, notice: 'Theater was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theater
      @theater = Theater.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theater_params
      params.require(:theater).permit(:state, :city, :latitude, :longitude, :theater_name, :zipcode)
    end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_form.html.erb
<%= form_with(model: theater, local: true) do |form| %>
  <% if theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% theater.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :theater_name %>
    <%= form.text_field :theater_name %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theaters/edit.html.erb
<p id="notice"><%= notice %></p>
<!-- only admin -->
<% if admin? %>
  <h1>Editing Theater</h1>

  <%= render 'form', theater: @theater %>

  <%= link_to 'Show', @theater %> |
  <%= link_to 'Back', theaters_path %>
<% end %>

app/views/theaters/index.html.erb
<h1>Theaters</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>State</th>
      <th>City</th>
      <th>Theater name</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theaters.each do |theater| %>
      <tr>
        <td><%= theater.state %></td>
        <td><%= theater.city %></td>
        <td><%= theater.theater_name %></td>
        <td><%= theater.zipcode %></td>

        <!-- only admin -->
        <% if admin? %>
          <td><%= link_to 'Edit', edit_theater_path(theater) %></td>
          <td><%= link_to 'Destroy', theater, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- only admin -->
<% if admin? %>
  <%= link_to 'Back', admin_dashboard_path %> |
  <%= link_to 'New Theater', new_theater_path %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/theaters/new.html.erb
<p id="notice"><%= notice %></p>
<!-- only admin -->
<% if admin? %>
  <h1>New Theater</h1>

  <%= render 'form', theater: @theater %>

  <%= link_to 'Back', theaters_path %>
<% end %>

app/views/theaters/show.html.erb
<p id="notice"><%= notice %></p>
<!-- only admin -->
<% if admin? %>
  <p>
    <strong>State:</strong>
    <%= @theater.state %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @theater.city %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @theater.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @theater.longitude %>
  </p>

  <p>
    <strong>Theater name:</strong>
    <%= @theater.theater_name %>
  </p>

  <p>
    <strong>Zipcode:</strong>
    <%= @theater.zipcode %>
  </p>

  <%= link_to 'Edit', edit_theater_path(@theater) %> |
  <%= link_to 'Back', theaters_path %>
<% end %>